SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


DROP DATABASE IF EXISTS restaurante;
CREATE DATABASE IF NOT EXISTS restaurante;
USE restaurante;

CREATE TABLE IF NOT EXISTS USERS (
	ID_USER INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Surnames VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Password VARCHAR(64) NOT NULL,
    Balance INT(5) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ;

CREATE TABLE IF NOT EXISTS ORDERS (
	ID_ORDER INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    ID_USER INT NOT NULL,
    First_Plate VARCHAR(30) NOT NULL,
    Second_Plate VARCHAR(30) NOT NULL,
    Dessert VARCHAR(30) NOT NULL,
    Price INT(3) NOT NULL,
	FOREIGN KEY (ID_USER) REFERENCES USERS (ID_USER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ;

CREATE TABLE IF NOT EXISTS EMAILS (
	ID_EMAIL INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    ID_USER INT NOT NULL,
    Origin_User VARCHAR(30) NOT NULL,
    Affair VARCHAR(30) NOT NULL,
    Message VARCHAR(255) NOT NULL,
    Email_Status BOOLEAN DEFAULT false,
	FOREIGN KEY (ID_USER) REFERENCES USERS (ID_USER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ;

INSERT INTO USERS (Name,Surnames,Email, Password) VALUE ('Ismael', 'Garcia Montero', 'ismagarmon3@gmail.com', '1234ismael');
INSERT INTO EMAILS (ID_USER,Origin_User,Affair,Message) VALUE (1,'Jose Luis','New email system','ASDASDASDASDASDASDASDASDASDASDASDASDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD')
