SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


DROP DATABASE IF EXISTS restaurante;
CREATE DATABASE IF NOT EXISTS restaurante;
USE restaurante;

CREATE TABLE IF NOT EXISTS USUARIOS (
	ID_USUARIO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL,
    Apellidos VARCHAR(100) NOT NULL,
    Correo VARCHAR(100) NOT NULL,
    Contraseña VARCHAR(64) NOT NULL,
    Saldo VARCHAR(5) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ;

CREATE TABLE IF NOT EXISTS PEDIDOS (
	ID_PEDIDO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    Primer_Plato VARCHAR(30) NOT NULL,
    Segundo_Plato VARCHAR(30) NOT NULL,
    Postre VARCHAR(30) NOT NULL,
    Precio INT(3) NOT NULL,
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ;
